name: Build and Tag

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: 0.1.0
          release_name: Release 0.1.0
          body: TIDAL plugin release
          draft: false
          prerelease: false

      - name: Setup Perl
        uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: '5.34'
          install-modules: XML::Simple Digest::SHA1

      - name: Zip repository
        id: zip
        run: zip TIDAL -r API *.pm ProtocolHandler HTML Settings install.xml

      - name: Update SHA in repo.xml
        id: tag
        run: |
          perl repo/release.pl TIDAL.zip

      
