name: Build and Tag

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Perl
        uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: '5.34'
          install-modules: XML::Simple Digest::SHA1

      - name: Zip repository
        id: zip
        run: zip TIDAL -r API *.pm ProtocolHandler HTML Settings install.xml

      - name: Update SHA in repo.xml
        id: tag
        run: |
          perl repo/release.pl TIDAL.zip

      - name: Upload ZIP asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.zip.upload_url }} 
          asset_path: ./TIDAL.zip
          asset_name: TIDAL.zip
          asset_content_type: application/octet-stream  
