name: Publish

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set Version
        id: set-version
        uses: actions/github-script@v6
        with:
            script: |
              const fs = require('fs');
              const xml = fs.readFileSync('install.xml', 'utf8');
              const version = xml.match(/<version>([^<]+)<\/version>/)[1];
              console.log(`::set-output name=version::${version}`);
        
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.set-version.outputs.version }}
          release_name: version ${{ steps.set-version.outputs.version }}
          body: TIDAL plugin release
          draft: false
          prerelease: false

      - name: Zip repository
        id: zip
        run: zip TIDAL -r API *.pm HTML Settings install.xml

      - name: Setup Perl
        uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: '5.34'
          install-modules: XML::Simple Digest::SHA1       

      - name: Update SHA and Version in repo.xml
        id: tag
        run: |
          url="https://github.com/${{ github.repository }}/releases/download/${{ steps.set-version.outputs.version }}"
          perl repo/release.pl repo/repo.xml ${{ steps.set-version.outputs.version }} TIDAL.zip $url

      - name: Update file
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add repo/repo.xml
          git commit -m "update repo.xml for release ${{ steps.set-version.outputs.version }}"
          git push origin HEAD:main
          
      - name: Upload Release Asset
        id: upload-release-asset 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} 
          asset_path: ./TIDAL.zip
          asset_name: TIDAL.zip
          asset_content_type: application/zip
          

      
