name: Build and Tag

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Zip repository
        run: zip -r repo.zip .

      - name: Set up Versio and SHA
        id: tag
        run: |
          pwd 
          ls -al
          #perl release.pl repo.zip

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: repo
          path: repo.zip
          
